### ISSUE TITLE
Binding jar file for use in openhab

### ISSUE THREAD

**Issue by HubertusH** [aleon-GmbH/aleoncean#11]
Hello, how can i get the .jar file to use your binding directly in openhab? i have no java environment to compile it by myself. Thanks.

**Comment by maggu2810** [comment]
Sorry, but we do not provide any compiled version of this code base. I have added a note to the README file of the project. As stated there, it is because of possible legal issues of the EnOcean Alliance.
See "Usage of EnOcean Equipment Profiles (EEP)" here https://www.enocean-alliance.org/en/member_benefits/
